import logging
import re
import json
import requests
from typing import Dict, Any

from schema import FileSpec, CodeGenContext, GeneratedFile
from prompts.codegen_prompt import CODEGEN_SYSTEM_PROMPT, build_codegen_prompt

logger = logging.getLogger(__name__)

class CodeGenAgent:
    def __init__(self, ollama_url: str, model: str):
        self.ollama_url = ollama_url
        self.model = model

    def execute(self, file_spec: FileSpec, context: CodeGenContext, existing_content: str = None) -> GeneratedFile:
        logger.info(f"Generating: {file_spec.path}")

        try:
            # Handle special files deterministically
            if file_spec.path == '.env':
                return self._generate_env_file(file_spec, context)
            if file_spec.path == 'package.json':
                return self._generate_package_json(file_spec, context)

            prompt = build_codegen_prompt(
                file_spec=file_spec,
                project_name=context.projectName,
                entities=context.entities,
                features=context.features,
                all_files=context.allFiles,
                existing_contents=context.existingFileContents,
                existing_file_content=existing_content
            )

            raw_response = self._query_ollama(prompt, CODEGEN_SYSTEM_PROMPT)

            code = self._extract_code(raw_response)

            if not code or len(code.strip()) < 10:
                raise ValueError(f"Generated code is too short ({len(code)} chars)")

            self._validate_code(file_spec.path, code)

            logger.info(f"✓ Generated: {file_spec.path} ({len(code)} chars)")

            return GeneratedFile(
                path=file_spec.path,
                content=code,
                status='generated'
            )

        except Exception as e:
            logger.error(f"✗ Failed to generate {file_spec.path}: {str(e)}")
            return GeneratedFile(
                path=file_spec.path,
                content='',
                status='error',
                errorMessage=str(e)
            )

    def _query_ollama(self, prompt: str, system_prompt: str) -> str:
        payload = {
            "model": self.model,
            "prompt": prompt,
            "system": system_prompt,
            "stream": False,
            "options": {
                "temperature": 0.3,
                "num_predict": 4096,
            }
        }
        resp = requests.post(
            f"{self.ollama_url}/api/generate",
            json=payload,
            timeout=120
        )
        resp.raise_for_status()
        data = resp.json()
        if "response" not in data:
            raise ValueError("Ollama returned no response")
        return data["response"]

    def _extract_code(self, raw_response: str) -> str:
        """Extracts code block from markdown if present."""
        code_match = re.search(r'```(?:javascript|js)?\s*(.*?)\s*```', raw_response, re.DOTALL | re.IGNORECASE)
        if code_match:
            return code_match.group(1).strip()
        return raw_response.strip()

    def _generate_env_file(self, file_spec: FileSpec, context: CodeGenContext) -> GeneratedFile:
        db_name = re.sub(r'[^a-z0-9]', '-', context.projectName.lower()).strip('-')
        has_auth = any('auth' in f.name.lower() for f in context.features)

        lines = [
            f"# {context.projectName} Environment Variables",
            "PORT=3000",
            f"MONGODB_URI=mongodb://localhost:27017/{db_name}",
            "NODE_ENV=development",
        ]

        if has_auth:
            lines.append("JWT_SECRET=your_jwt_secret_key_change_in_production")
            lines.append("JWT_EXPIRE=7d")

        lines.append("")
        content = "\n".join(lines)
        
        logger.info(f"✓ Generated: {file_spec.path} (env file — deterministic)")
        return GeneratedFile(path=file_spec.path, content=content, status='generated')

    def _generate_package_json(self, file_spec: FileSpec, context: CodeGenContext) -> GeneratedFile:
        has_auth = any('auth' in f.name.lower() for f in context.features)
        has_validation = any('valid' in f.name.lower() for f in context.features)

        pkg = {
            "name": context.projectName,
            "version": "1.0.0",
            "description": f"{context.projectName} — Generated by AI Backend Builder",
            "type": "module",
            "main": "app.js",
            "scripts": {
                "start": "node app.js",
                "dev": "node --watch app.js"
            },
            "dependencies": {
                "express": "^4.18.2",
                "mongoose": "^8.0.0",
                "dotenv": "^16.3.1",
                "cors": "^2.8.5"
            }
        }

        if has_auth:
            pkg["dependencies"]["bcryptjs"] = "^2.4.3"
            pkg["dependencies"]["jsonwebtoken"] = "^9.0.2"
        if has_validation:
            pkg["dependencies"]["express-validator"] = "^7.0.1"

        content = json.dumps(pkg, indent=2) + "\n"
        
        logger.info(f"✓ Generated: {file_spec.path} (package.json — deterministic)")
        return GeneratedFile(path=file_spec.path, content=content, status='generated')

    def _validate_code(self, path: str, code: str):
        warnings = []
        
        if 'require(' in code and 'import ' in code:
            warnings.append("Mixed require() and import statements detected")
        if 'require(' in code and 'import ' not in code:
            warnings.append("Using require() instead of ES module imports")
        if 'module.exports' in code:
            warnings.append("Using module.exports instead of ES module exports")
        if '// TODO' in code or '/* TODO' in code:
            warnings.append("Contains TODO placeholders")

        import_regex = re.compile(r"from\s+['\"](\.\/.+?)['\"]")
        for match in import_regex.finditer(code):
            import_path = match.group(1)
            if not import_path.endswith('.js') and not import_path.endswith('.json'):
                warnings.append(f"Import '{import_path}' missing .js extension")

        for w in warnings:
            logger.warning(f"{path}: {w}")
